package com.aihu.model;

import java.util.Date;

public class AdminStructer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_admin_structer.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_admin_structer.pid
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_admin_structer.structer_name
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String structer_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_admin_structer.comment
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_admin_structer.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_admin_structer.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_admin_structer.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_admin_structer.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Byte del_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_admin_structer.id
     *
     * @return the value of b_admin_structer.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_admin_structer.id
     *
     * @param id the value for b_admin_structer.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_admin_structer.pid
     *
     * @return the value of b_admin_structer.pid
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_admin_structer.pid
     *
     * @param pid the value for b_admin_structer.pid
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_admin_structer.structer_name
     *
     * @return the value of b_admin_structer.structer_name
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getStructer_name() {
        return structer_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_admin_structer.structer_name
     *
     * @param structer_name the value for b_admin_structer.structer_name
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setStructer_name(String structer_name) {
        this.structer_name = structer_name == null ? null : structer_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_admin_structer.comment
     *
     * @return the value of b_admin_structer.comment
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_admin_structer.comment
     *
     * @param comment the value for b_admin_structer.comment
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_admin_structer.create_time
     *
     * @return the value of b_admin_structer.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_admin_structer.create_time
     *
     * @param create_time the value for b_admin_structer.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_admin_structer.update_time
     *
     * @return the value of b_admin_structer.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_admin_structer.update_time
     *
     * @param update_time the value for b_admin_structer.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_admin_structer.modifier
     *
     * @return the value of b_admin_structer.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_admin_structer.modifier
     *
     * @param modifier the value for b_admin_structer.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_admin_structer.del_flag
     *
     * @return the value of b_admin_structer.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Byte getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_admin_structer.del_flag
     *
     * @param del_flag the value for b_admin_structer.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setDel_flag(Byte del_flag) {
        this.del_flag = del_flag;
    }
}