package com.aihu.model;

import java.util.Date;

public class DeviceActionFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_action_flow.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_action_flow.device_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String device_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_action_flow.action_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer action_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_action_flow.record_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date record_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_action_flow.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_action_flow.id
     *
     * @return the value of b_device_action_flow.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_action_flow.id
     *
     * @param id the value for b_device_action_flow.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_action_flow.device_id
     *
     * @return the value of b_device_action_flow.device_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getDevice_id() {
        return device_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_action_flow.device_id
     *
     * @param device_id the value for b_device_action_flow.device_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setDevice_id(String device_id) {
        this.device_id = device_id == null ? null : device_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_action_flow.action_id
     *
     * @return the value of b_device_action_flow.action_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getAction_id() {
        return action_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_action_flow.action_id
     *
     * @param action_id the value for b_device_action_flow.action_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setAction_id(Integer action_id) {
        this.action_id = action_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_action_flow.record_time
     *
     * @return the value of b_device_action_flow.record_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getRecord_time() {
        return record_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_action_flow.record_time
     *
     * @param record_time the value for b_device_action_flow.record_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setRecord_time(Date record_time) {
        this.record_time = record_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_action_flow.create_time
     *
     * @return the value of b_device_action_flow.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_action_flow.create_time
     *
     * @param create_time the value for b_device_action_flow.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}