package com.aihu.model;

import java.util.Date;

public class DeviceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_info.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_info.device_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String device_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_info.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_info.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_info.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_info.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Byte del_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_info.id
     *
     * @return the value of b_device_info.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_info.id
     *
     * @param id the value for b_device_info.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_info.device_id
     *
     * @return the value of b_device_info.device_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getDevice_id() {
        return device_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_info.device_id
     *
     * @param device_id the value for b_device_info.device_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setDevice_id(String device_id) {
        this.device_id = device_id == null ? null : device_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_info.create_time
     *
     * @return the value of b_device_info.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_info.create_time
     *
     * @param create_time the value for b_device_info.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_info.update_time
     *
     * @return the value of b_device_info.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_info.update_time
     *
     * @param update_time the value for b_device_info.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_info.modifier
     *
     * @return the value of b_device_info.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_info.modifier
     *
     * @param modifier the value for b_device_info.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_info.del_flag
     *
     * @return the value of b_device_info.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Byte getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_info.del_flag
     *
     * @param del_flag the value for b_device_info.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setDel_flag(Byte del_flag) {
        this.del_flag = del_flag;
    }
}