package com.aihu.model;

public class StaffKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_key.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_key.staff_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer staff_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_key.id
     *
     * @return the value of b_staff_key.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_key.id
     *
     * @param id the value for b_staff_key.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_key.staff_id
     *
     * @return the value of b_staff_key.staff_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getStaff_id() {
        return staff_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_key.staff_id
     *
     * @param staff_id the value for b_staff_key.staff_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setStaff_id(Integer staff_id) {
        this.staff_id = staff_id;
    }
}