package com.aihu.model;

import java.util.Date;

public class StaffPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_permission.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_permission.staff_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer staff_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_permission.oper_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer oper_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_permission.scope_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer scope_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_permission.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_permission.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_permission.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_staff_permission.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Byte del_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_permission.id
     *
     * @return the value of b_staff_permission.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_permission.id
     *
     * @param id the value for b_staff_permission.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_permission.staff_id
     *
     * @return the value of b_staff_permission.staff_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getStaff_id() {
        return staff_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_permission.staff_id
     *
     * @param staff_id the value for b_staff_permission.staff_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setStaff_id(Integer staff_id) {
        this.staff_id = staff_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_permission.oper_id
     *
     * @return the value of b_staff_permission.oper_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getOper_id() {
        return oper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_permission.oper_id
     *
     * @param oper_id the value for b_staff_permission.oper_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setOper_id(Integer oper_id) {
        this.oper_id = oper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_permission.scope_id
     *
     * @return the value of b_staff_permission.scope_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getScope_id() {
        return scope_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_permission.scope_id
     *
     * @param scope_id the value for b_staff_permission.scope_id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setScope_id(Integer scope_id) {
        this.scope_id = scope_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_permission.create_time
     *
     * @return the value of b_staff_permission.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_permission.create_time
     *
     * @param create_time the value for b_staff_permission.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_permission.update_time
     *
     * @return the value of b_staff_permission.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_permission.update_time
     *
     * @param update_time the value for b_staff_permission.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_permission.modifier
     *
     * @return the value of b_staff_permission.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_permission.modifier
     *
     * @param modifier the value for b_staff_permission.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_staff_permission.del_flag
     *
     * @return the value of b_staff_permission.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Byte getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_staff_permission.del_flag
     *
     * @param del_flag the value for b_staff_permission.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setDel_flag(Byte del_flag) {
        this.del_flag = del_flag;
    }
}