package com.aihu.model;

import java.util.Date;

public class UserAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_action.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_action.action_name
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String action_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_action.comment
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_action.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_action.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_action.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_action.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Byte del_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_action.id
     *
     * @return the value of c_user_action.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_action.id
     *
     * @param id the value for c_user_action.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_action.action_name
     *
     * @return the value of c_user_action.action_name
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getAction_name() {
        return action_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_action.action_name
     *
     * @param action_name the value for c_user_action.action_name
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setAction_name(String action_name) {
        this.action_name = action_name == null ? null : action_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_action.comment
     *
     * @return the value of c_user_action.comment
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_action.comment
     *
     * @param comment the value for c_user_action.comment
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_action.create_time
     *
     * @return the value of c_user_action.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_action.create_time
     *
     * @param create_time the value for c_user_action.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_action.update_time
     *
     * @return the value of c_user_action.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_action.update_time
     *
     * @param update_time the value for c_user_action.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_action.modifier
     *
     * @return the value of c_user_action.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_action.modifier
     *
     * @param modifier the value for c_user_action.modifier
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_action.del_flag
     *
     * @return the value of c_user_action.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Byte getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_action.del_flag
     *
     * @param del_flag the value for c_user_action.del_flag
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setDel_flag(Byte del_flag) {
        this.del_flag = del_flag;
    }
}