package com.aihu.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.openid
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.nick_name
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String nick_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.gender
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.country
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.province
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.city
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.avatar_url
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private String avatar_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_info.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.id
     *
     * @return the value of c_user_info.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.id
     *
     * @param id the value for c_user_info.id
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.openid
     *
     * @return the value of c_user_info.openid
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.openid
     *
     * @param openid the value for c_user_info.openid
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.nick_name
     *
     * @return the value of c_user_info.nick_name
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getNick_name() {
        return nick_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.nick_name
     *
     * @param nick_name the value for c_user_info.nick_name
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setNick_name(String nick_name) {
        this.nick_name = nick_name == null ? null : nick_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.gender
     *
     * @return the value of c_user_info.gender
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.gender
     *
     * @param gender the value for c_user_info.gender
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.country
     *
     * @return the value of c_user_info.country
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.country
     *
     * @param country the value for c_user_info.country
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.province
     *
     * @return the value of c_user_info.province
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.province
     *
     * @param province the value for c_user_info.province
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.city
     *
     * @return the value of c_user_info.city
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.city
     *
     * @param city the value for c_user_info.city
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.avatar_url
     *
     * @return the value of c_user_info.avatar_url
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public String getAvatar_url() {
        return avatar_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.avatar_url
     *
     * @param avatar_url the value for c_user_info.avatar_url
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setAvatar_url(String avatar_url) {
        this.avatar_url = avatar_url == null ? null : avatar_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.create_time
     *
     * @return the value of c_user_info.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.create_time
     *
     * @param create_time the value for c_user_info.create_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_info.update_time
     *
     * @return the value of c_user_info.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_info.update_time
     *
     * @param update_time the value for c_user_info.update_time
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}