package com.aihu.dao;

import com.aihu.model.AdminOper;

public interface AdminOperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_oper
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_oper
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insert(AdminOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_oper
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insertSelective(AdminOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_oper
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    AdminOper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_oper
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(AdminOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_oper
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKey(AdminOper record);
}