package com.aihu.dao;

import com.aihu.model.AdminStructer;

public interface AdminStructerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_structer
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_structer
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insert(AdminStructer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_structer
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insertSelective(AdminStructer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_structer
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    AdminStructer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_structer
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(AdminStructer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_admin_structer
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKey(AdminStructer record);
}