package com.aihu.dao;

import com.aihu.model.DeviceAction;

public interface DeviceActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insert(DeviceAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insertSelective(DeviceAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    DeviceAction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(DeviceAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKey(DeviceAction record);
}