package com.aihu.dao;

import com.aihu.model.DeviceInfo;

public interface DeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_info
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_info
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insert(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_info
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insertSelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_info
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    DeviceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_info
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_info
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKey(DeviceInfo record);
}