package com.aihu.dao;

import com.aihu.model.DeviceActionFlow;

public interface DeviceActionFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insert(DeviceActionFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insertSelective(DeviceActionFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    DeviceActionFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(DeviceActionFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_device_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKey(DeviceActionFlow record);
}