package com.aihu.dao;

import com.aihu.model.StaffPermission;

public interface StaffPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_permission
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_permission
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insert(StaffPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_permission
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insertSelective(StaffPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_permission
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    StaffPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_permission
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(StaffPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_permission
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKey(StaffPermission record);
}