package com.aihu.dao;

import com.aihu.model.StaffKey;

public interface StaffKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_key
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_key
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insert(StaffKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_key
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insertSelective(StaffKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_key
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    StaffKey selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_key
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(StaffKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_staff_key
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKey(StaffKey record);
}