package com.aihu.dao;

import com.aihu.model.UserActionFlow;

public interface UserActionFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insert(UserActionFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insertSelective(UserActionFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    UserActionFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(UserActionFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action_flow
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKey(UserActionFlow record);
}