package com.aihu.dao;

import com.aihu.model.UserAction;

public interface UserActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insert(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int insertSelective(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    UserAction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_action
     *
     * @mbggenerated Sun Jun 23 02:48:58 CST 2019
     */
    int updateByPrimaryKey(UserAction record);
}